// 1. Grab all required HTML elements via the DOM
const astroForm = document.getElementById('astroForm');
const loadingContainer = document.getElementById('loadingContainer');
const resultCard = document.getElementById('resultCard');
const readingOutput = document.getElementById('readingOutput');
const resetBtn = document.getElementById('resetBtn');

// 2. Add an Event Listener to handle form submission
astroForm.addEventListener('submit', async function (event) {
    
    // Stop the browser from reloading the page automatically
    event.preventDefault();

    // 3. Extract the text values entered by the user
    const name = document.getElementById('userName').value;
    const dob = document.getElementById('birthDate').value;
    const time = document.getElementById('birthTime').value;
    const place = document.getElementById('birthPlace').value;

    // 4. Update UI State: Hide the form, reveal the loading spinner
    astroForm.classList.add('hidden');
    loadingContainer.classList.remove('hidden');

    // 5. Build a custom, highly detailed prompt for the AI model
    const cosmicPrompt = `You are an expert Vedic Astrologer. Generate a highly personalized Kundali reading and personality breakdown based on these exact details:
    Name: ${name}
    Date of Birth: ${dob}
    Time of Birth: ${time}
    Place of Birth: ${place}
    
    Please organize your reading into 3 clear sections:
    1. 🌌 Planetary Alignment Overview (Talk about their general energy)
    2. 💼 Career & 💖 Relationship Forecast (What does the future hold?)
    3. 🔮 Cosmic Tip of the Week (One actionable piece of advice)
    
    Keep the tone mysterious, encouraging, and deeply insightful. Use clear line breaks between sections.`;

    // 6. Trigger the Asynchronous API network call using Try/Catch/Finally
    try {
        // FIXED: Swapped out OpenAI for Hugging Face Endpoint
        // const response = await fetch('https://huggingface.co', {
              // Re-write the fetch request cleanly
        const response = await fetch("https://huggingface.co", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': 'Bearer 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' 
            },
            body: JSON.stringify({
                model: "meta-llama/Meta-Llama-3-8B-Instruct", 
                messages: [{ role: "user", content: cosmicPrompt }],
                temperature: 0.7 
            })
        });


        // Convert the incoming raw data stream into a readable JSON object
        const data = await response.json();

        // Check if the API returned an error (e.g., bad key or network issue)
        if (!response.ok) {
            throw new Error(data.error ? data.error.message : "Failed to connect to the cosmos.");
        }

        // Extract the textual response string generated by ChatGPT
        const aiReading = data.choices[0].message.content;

        // Inject the text response into our output container element
        readingOutput.textContent = aiReading;

        // Reveal the result card panel to the user
        resultCard.classList.remove('hidden');

    } catch (error) {
        // If anything goes wrong in the 'try' block, execution drops straight down here
        console.error("Cosmic Error Logged:", error);
        readingOutput.innerHTML = `<span style="color: #ff4d4d; font-weight: bold;">⚠️ The stars are misaligned:</span> ${error.message}. Please verify your API key and try again!`;
        resultCard.classList.remove('hidden');
    } finally {
        // This block ALWAYS runs no matter what, whether the API call succeeded or failed!
        // It turns off our spinning loading indicator
        loadingContainer.classList.add('hidden');
    }
});

// 7. Add an Event Listener to the Reset Button to allow re-testing
resetBtn.addEventListener('click', function() {
    resultCard.classList.add('hidden'); // Hide the result view
    astroForm.reset();                  // Completely clear all the form fields
    astroForm.classList.remove('hidden'); // Bring back the clean input form
});
